baseURL = 'https://fengtianwu.github.io/'
languageCode = 'en-us'
theme = 'ananke'
title = 'Home'

SectionPagesMenu = "main"
Paginate = 9 
#googleAnalytics = ""
enableRobotsTXT = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "fengtianwu"
  favicon = ""
  site_logo = ""
  background_color_class = "bg-dark-green"
  recent_posts_number = 1

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/fengtianwu"



